version: '3.1'

services:
  server:
    image: "barumel/docker-astroneer-server:latest"
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - "SERVER_PORT=${SERVER_PORT}"
      - "SERVER_NAME=${SERVER_NAME}"
      - "SERVER_PASSWORD=${SERVER_PASSWORD}"
      - "OWNER_NAME=${OWNER_NAME}"
      - "TZ=${TZ}"
    ports:
      - 8777:8777/tcp
      - 8777:8777/udp
    volumes:
     - astroneer:/astroneer
     - steamcmd:/steamcmd
     - wine:/wine
     - backup:/backup

volumes:
  astroneer:
  steamcmd:
  wine:
  backup:
