version: '3.1'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - "SERVER_PORT=8777"
      - "SERVER_PUBLIC_IP="
      - "SERVER_NAME=SAY_MY_NAME"
      - "SERVER_PASSWORD=MySuperSecurePassword"
      - "OWNER_NAME=Dr. Evil"
    ports:
      - 8777:8777/tcp
      - 8777:8777/udp
    volumes:
     - astroneer:/astroneer
     - steamcmd:/steamcmd
     - wine:/wine
     - backup:/backup

volumes:
  astroneer:
  steamcmd:
  wine:
  backup:
